repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check --fix --show-fixes
        language: system
        types: [python]
        args: [--config=pyproject.toml]
        require_serial: true
        stages: [commit, push]

      - id: ruff-format
        name: ruff-format
        entry: ruff format
        language: system
        types: [python]
        args: [--config=pyproject.toml]
        require_serial: true
        stages: [commit, push]

  - repo: local
    hooks:
      - id: frontend-lint
        name: frontend-lint
        entry: bash -c 'cd ../frontend && bun lint'
        language: system
        types: [javascript, typescript, json, css, scss, html]
        pass_filenames: false
        require_serial: true
        stages: [commit, push]

      - id: frontend-type-check
        name: frontend-type-check
        entry: bash -c 'cd ../frontend && bun run type-check'
        language: system
        types: [typescript]
        pass_filenames: false
        require_serial: true
        stages: [commit, push]